### PR TITLE
Updating heroku python runtime

### PR DESCRIPTION
**Pull request by alexbarbato**
Trying to get a deployment of this up for Maggie to use in her new adventures so cleaning up some minor things.

Is it possible to add me as a maintainer please @jcarbaugh / @scottpdo?

### CODE REVIEW

**Comment by alexbarbato** [comment]
PS: If you have any easy intuitions as to why Heroku is defaulting to Django 3+ when I use the deploy to heroku button that would be greatly appreciated!

The Pipfile seems to pretty clearly say less than 2.3, unless I'm misreading it 0.o

**Comment by scottpdo** [comment]
@alexbarbato I'll leave the weird Heroku bizness to @jcarbaugh but I just added you as an admin (as it should be, this is your baby!)

**Comment by jcarbaugh** [comment]
@alexbarbato no idea why it might be installing Python 2! Could add me as a collaborator on the Heroku app so I can see some build logs?

**Comment by alexbarbato** [comment]
@jcarbaugh - thanks! I added you as a collaborator if you're curious.

I ended up fixing it by locking the version to Django 2 LTS and pushing the Pipfile.lock.. so 🤷‍♂

**Comment by jcarbaugh** [comment]
@alexbarbato so weird! I installed it locally and it only had Django 2, but when I deployed it to Heroku it had installed both 2 and 3. Glad you could lock it!

**Comment by alexbarbato** [comment]
Thanks for trying to see what was going on @jcarbaugh!

**Pull request merged**
